### ISSUE TITLE
Check out new Nutch Miredot REST API docs

### ISSUE THREAD

**Issue by chrismattmann** [memex-explorer/nutch-python#16]
@ahmadia scope this out:

http://people.apache.org/~lewismc/miredot/#-63064223

**Comment by ahmadia** [comment]
Sweet.  Will this go into Nutch official documentation somewhere?

**Comment by chrismattmann** [comment]
yep that's the goal is to build it as part of the official Nutch docs! cc @lewismc @ahmadia

**Comment by lewismc** [comment]
Bewm

On Thursday, October 29, 2015, Chris Mattmann notifications@github.com
wrote:

> yep that's the goal is to build it as part of the official Nutch docs! cc
> @lewismc https://github.com/lewismc @ahmadia
> https://github.com/ahmadia
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/memex-explorer/nutch-python/issues/16#issuecomment-152197689
> .

## 

_Lewis_

**Comment by chrismattmann** [comment]
now part of official Nutch docs!
