### ISSUE TITLE
Deprecate namespace package

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/nutch-python#2]
Namespace packages are a non-standard feature in Python, and should only be used if there's a legitimate reason.  Since now nutch-python seems to be a single-module installation, I think we should deprecate this unless I'm missing something (in which case, please correct me).

**Comment by chrismattmann** [comment]
hey @ahmadia where are we using namespace_packages? I don't think it uses those, right?

**Comment by ahmadia** [comment]
See `__init__.py`

**Comment by ahmadia** [comment]
https://github.com/memex-explorer/nutch-python/blob/master/nutch/__init__.py#L17

**Comment by chrismattmann** [comment]
hmm got it. Pull request to update?

**Comment by ahmadia** [comment]
yeah, it's on my list

**Comment by ahmadia** [comment]
done in b2035f583e280ab88d3ba506a046e0c80dc9cd19
